import { WeeklyPlan, Workout } from './schemas';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

// ── Markdown export ─────────────────────────────────────────────────────────

export function workoutToMarkdown(workout: Workout): string {
  const lines: string[] = [
    `# ${workout.title}`,
    `**Duration:** ${workout.totalTime} minutes`,
    '',
  ];
  for (const section of workout.sections) {
    lines.push(`## ${section.name}`);
    lines.push('');
    lines.push('| Exercise | Reps / Duration | Rest | Notes |');
    lines.push('|----------|----------------|------|-------|');
    for (const ex of section.exercises) {
      const metric = ex.reps ? `${ex.reps} reps` : ex.duration || '—';
      const notes = ex.instructions || '—';
      lines.push(`| ${ex.name} | ${metric} | ${ex.rest} | ${notes} |`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

export function weeklyPlanToMarkdown(plan: WeeklyPlan): string {
  const lines: string[] = [
    `# ${plan.weekTitle}`,
    `**Goal:** ${plan.goal}`,
    '',
    '---',
    '',
  ];
  for (const day of plan.days) {
    if (day.isRest) {
      lines.push(`## ${day.day} — 🛌 Rest Day`);
      lines.push('');
      lines.push('*Recovery & muscle repair. Stay hydrated and get quality sleep.*');
      lines.push('');
    } else if (day.workout) {
      lines.push(`## ${day.day} — ${day.focus}`);
      lines.push('');
      lines.push(workoutToMarkdown(day.workout).replace(/^# .+\n/, '').trim());
      lines.push('');
    }
    lines.push('---');
    lines.push('');
  }
  lines.push(`*Generated by FitForge AI — ${new Date().toLocaleDateString()}*`);
  return lines.join('\n');
}

// ── Plain Text export ────────────────────────────────────────────────────────

export function workoutToText(workout: Workout): string {
  const lines: string[] = [
    `FITFORGE WORKOUT: ${workout.title.toUpperCase()}`,
    `Duration: ${workout.totalTime} minutes`,
    '='.repeat(40),
    '',
  ];
  for (const section of workout.sections) {
    lines.push(`[ ${section.name.toUpperCase()} ]`);
    lines.push('');
    for (const ex of section.exercises) {
      const metric = ex.reps ? `${ex.reps} reps` : ex.duration || '—';
      lines.push(`${ex.name.padEnd(25)} | ${metric.padEnd(12)} | Rest: ${ex.rest}`);
      if (ex.instructions) lines.push(`  Notes: ${ex.instructions}`);
      lines.push('');
    }
  }
  return lines.join('\n');
}

export function weeklyPlanToText(plan: WeeklyPlan): string {
  const lines: string[] = [
    `FITFORGE WEEKLY PLAN: ${plan.weekTitle.toUpperCase()}`,
    `Goal: ${plan.goal}`,
    '='.repeat(40),
    '',
  ];
  for (const day of plan.days) {
    lines.push(`--- ${day.day.toUpperCase()} ---`);
    if (day.isRest) {
      lines.push('REST DAY: Neural Recovery & Muscle Repair');
    } else if (day.workout) {
      lines.push(`FOCUS: ${day.focus}`);
      lines.push('');
      lines.push(workoutToText(day.workout).split('='.repeat(40))[1]?.trim() || '');
    }
    lines.push('');
  }
  lines.push(`Generated by FitForge AI on ${new Date().toLocaleDateString()}`);
  return lines.join('\n');
}

// ── HTML export ─────────────────────────────────────────────────────────────

// Design tokens — all colours as 6-digit hex so html2canvas never chokes
const C = {
  bg:           '#1c1c20',
  card:         '#222227',
  border:       '#2e2e35',
  muted:        '#28282e',
  fg:           '#fafafa',
  fgMuted:      '#888893',
  primary:      '#a8e062',
  primaryBg:    '#1f2e11',  // approx rgba(168,224,98,0.10) on dark bg
  primaryBdr:   '#3a5020',  // approx rgba(168,224,98,0.25) on dark bg
  numBadgeFg:   '#0f1a00',
};

// Shared inline styles as JS objects → converted to style strings
const S = {
  page:      `max-width:794px;margin:0 auto;padding:36px 28px;font-family:'Inter',-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:${C.bg};color:${C.fg};line-height:1.5;`,
  pill:      `display:inline-block;padding:5px 14px;border-radius:999px;border:1px solid ${C.primaryBdr};background:${C.primaryBg};color:${C.primary};font-size:10px;font-weight:800;letter-spacing:0.18em;text-transform:uppercase;margin-bottom:18px;`,
  h1:        `font-size:40px;font-weight:900;letter-spacing:-0.03em;line-height:1.1;margin:0 0 8px;color:${C.fg};`,
  subtitle:  `color:${C.fgMuted};font-size:14px;margin:0 0 36px;`,

  // Section divider — table-based, no pseudo elements
  divWrap:   `display:table;width:100%;margin:32px 0 16px;border-collapse:collapse;`,
  divLine:   `display:table-cell;border-top:1px solid ${C.border};vertical-align:middle;width:50%;`,
  divLabel:  `display:table-cell;padding:0 14px;white-space:nowrap;font-size:10px;font-weight:900;letter-spacing:0.25em;text-transform:uppercase;color:${C.fgMuted};border:1px solid ${C.border};border-radius:999px;background:${C.muted};vertical-align:middle;text-align:center;`,

  // Exercise card — table layout for reliable two-column split
  exCard:    `background:${C.card};border:1px solid ${C.border};border-radius:14px;margin-bottom:10px;overflow:hidden;`,
  exTable:   `display:table;width:100%;border-collapse:collapse;padding:18px 20px;`,
  exLeft:    `display:table-cell;vertical-align:top;width:100%;`,
  exRight:   `display:table-cell;vertical-align:middle;white-space:nowrap;padding-left:16px;text-align:right;`,

  // Number badge
  numBadge:  `display:inline-block;width:30px;height:30px;border-radius:8px;background:${C.primary};color:${C.numBadgeFg};font-size:12px;font-weight:900;border:1px solid ${C.primaryBdr};text-align:center;line-height:30px;vertical-align:top;flex-shrink:0;`,
  exNameWrap:`display:inline-block;vertical-align:top;padding-left:12px;`,
  exName:    `font-size:16px;font-weight:800;color:${C.fg};letter-spacing:-0.02em;line-height:1.3;`,
  exNote:    `font-size:12px;color:${C.fgMuted};font-style:italic;margin-top:3px;`,

  // Badges (right column)
  badgeSets: `display:inline-block;padding:4px 9px;border-radius:7px;font-size:10px;font-weight:900;letter-spacing:0.12em;text-transform:uppercase;border:1px solid ${C.border};background:${C.muted};color:${C.fg};white-space:nowrap;`,
  badgeReps: `display:inline-block;padding:4px 9px;border-radius:7px;font-size:10px;font-weight:900;letter-spacing:0.12em;text-transform:uppercase;border:1px solid ${C.primaryBdr};background:${C.primaryBg};color:${C.primary};white-space:nowrap;margin-left:5px;`,
  badgeRest: `display:block;margin-top:7px;font-size:10px;font-weight:700;color:${C.fgMuted};letter-spacing:0.1em;text-transform:uppercase;text-align:right;`,
  restIcon:  `color:${C.primary};`,

  // Day card
  dayCard:   `border:1px solid ${C.border};border-radius:16px;overflow:hidden;margin-bottom:14px;background:${C.card};`,
  dayHeader: `display:table;width:100%;border-collapse:collapse;padding:16px 20px;border-bottom:1px solid ${C.border};box-sizing:border-box;`,
  dayLeft:   `display:table-cell;vertical-align:middle;`,
  dayName:   `display:inline-block;font-size:11px;font-weight:900;letter-spacing:0.18em;text-transform:uppercase;color:${C.fgMuted};min-width:80px;vertical-align:middle;`,
  dayFocus:  `display:inline-block;font-size:10px;font-weight:900;letter-spacing:0.15em;text-transform:uppercase;padding:4px 11px;border-radius:7px;border:1px solid ${C.primaryBdr};background:${C.primaryBg};color:${C.primary};vertical-align:middle;`,
  dayDur:    `display:inline-block;font-size:11px;font-weight:700;color:${C.fgMuted};margin-left:10px;vertical-align:middle;`,
  dayRest:   `display:inline-block;font-size:10px;font-weight:900;letter-spacing:0.15em;text-transform:uppercase;padding:4px 11px;border-radius:7px;border:1px solid ${C.border};background:${C.muted};color:${C.fgMuted};vertical-align:middle;`,
  dayBody:   `padding:14px 20px 18px;`,

  // Week strip
  stripWrap: `display:table;width:100%;border-collapse:separate;border-spacing:7px 0;margin:0 -7px 32px;`,
  stripCell: `display:table-cell;text-align:center;padding:10px 4px;border-radius:12px;vertical-align:middle;`,
  stripCellA:`border:1px solid ${C.primaryBdr};background:${C.primaryBg};`,
  stripCellR:`border:1px solid ${C.border};background:${C.muted};opacity:0.5;`,
  stripDay:  `font-size:9px;font-weight:900;letter-spacing:0.15em;text-transform:uppercase;color:${C.fgMuted};display:block;`,
  stripDot:  `width:5px;height:5px;border-radius:50%;margin:5px auto;`,
  stripFocA: `font-size:8px;font-weight:900;text-transform:uppercase;color:${C.primary};display:block;margin-top:2px;`,
  stripFocR: `font-size:8px;font-weight:900;text-transform:uppercase;color:${C.fgMuted};display:block;margin-top:2px;`,

  footer:    `margin-top:48px;padding-top:18px;border-top:1px solid ${C.border};text-align:center;font-size:10px;font-weight:800;letter-spacing:0.4em;text-transform:uppercase;color:${C.fgMuted};`,
};

type ExArg = { name: string; sets?: string | null; reps?: string | null; duration?: string | null; rest: string; instructions?: string | null };

function cleanRest(rest: string): string {
  if (!rest || rest === 'N/A' || rest === 'n/a' || rest === '—') return '';
  return rest;
}

function renderExerciseCard(ex: ExArg, idx: number): string {
  const setsHtml  = ex.sets ? `<span style="${S.badgeSets}">${ex.sets} SETS</span>` : '';
  // Truncate very long rep strings, always append unit label
  const rawReps     = ex.reps ?? '';
  const rawDuration = ex.duration ?? '';
  const shortReps     = rawReps.length > 14 ? rawReps.slice(0, 13) + '…' : rawReps;
  const shortDuration = rawDuration.length > 14 ? rawDuration.slice(0, 13) + '…' : rawDuration;
  const targetHtml = rawReps
    ? `<span style="${S.badgeReps}">${shortReps} REPS</span>`
    : rawDuration
      ? `<span style="${S.badgeReps}">${shortDuration}</span>`
      : '';
  const rest = cleanRest(ex.rest);
  const restHtml = rest ? `<span style="${S.badgeRest}"><span style="${S.restIcon}">⏱</span> REST ${rest}</span>` : '';

  return `
<div style="${S.exCard}">
  <div style="${S.exTable}">
    <div style="${S.exLeft}">
      <span style="${S.numBadge}">${idx + 1}</span>
      <span style="${S.exNameWrap}">
        <div style="${S.exName}">${ex.name}</div>
        ${ex.instructions ? `<div style="${S.exNote}">${ex.instructions}</div>` : ''}
      </span>
    </div>
    <div style="${S.exRight}">
      ${setsHtml}${targetHtml}
      ${restHtml}
    </div>
  </div>
</div>`;
}

type SectionArg = { name: string; exercises: ExArg[] };

function renderSections(sections: SectionArg[]): string {
  return sections.map(section => {
    const exercises = section.exercises.map((ex, i) => renderExerciseCard(ex, i)).join('');
    return `
<div style="${S.divWrap}">
  <div style="${S.divLine}"></div>
  <div style="${S.divLabel}">${section.name}</div>
  <div style="${S.divLine}"></div>
</div>
${exercises}`;
  }).join('');
}

const HTML_HEAD = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700;800;900&display=swap" rel="stylesheet">
  <style>
    *,*::before,*::after{box-sizing:border-box;margin:0;padding:0;}
    body{background:${C.bg};-webkit-print-color-adjust:exact;print-color-adjust:exact;}
  </style>`;

export function workoutToHtml(workout: Workout): string {
  return `${HTML_HEAD}
  <title>${workout.title} | FitForge AI</title>
</head>
<body>
  <div style="${S.page}">
    <div style="${S.pill}">● FitForge AI · Single Session</div>
    <h1 style="${S.h1}">${workout.title}</h1>
    <p style="${S.subtitle}">⏱ ${workout.totalTime}-minute session</p>
    ${renderSections(workout.sections)}
    <div style="${S.footer}">© ${new Date().getFullYear()} FitForge AI · Engineering Excellence in Fitness</div>
  </div>
</body>
</html>`;
}

export function weeklyPlanToHtml(plan: WeeklyPlan): string {
  const activeDays = plan.days.filter(d => !d.isRest).length;

  const stripHtml = `<div style="${S.stripWrap}">${
    plan.days.map(d => {
      const focusLabel = d.isRest ? '—' : (d.focus.length > 6 ? d.focus.split(' ')[0] : d.focus);
      return `<div style="${S.stripCell}${d.isRest ? S.stripCellR : S.stripCellA}">
        <span style="${S.stripDay}">${d.day.slice(0, 3)}</span>
        <div style="${S.stripDot};background:${d.isRest ? C.fgMuted : C.primary};"></div>
        <span style="${d.isRest ? S.stripFocR : S.stripFocA}">${focusLabel}</span>
      </div>`;
    }).join('')
  }</div>`;

  const daysHtml = plan.days.map(day => {
    const header = day.isRest
      ? `<div style="${S.dayLeft}">
           <span style="${S.dayName}">${day.day}</span>
           <span style="${S.dayRest}">🌙 Neural Recovery</span>
         </div>`
      : `<div style="${S.dayLeft}">
           <span style="${S.dayName}">${day.day}</span>
           <span style="${S.dayFocus}">${day.focus}</span>
           <span style="${S.dayDur}">⏱ ${day.workout?.totalTime ?? '?'}m</span>
         </div>`;

    const body = (!day.isRest && day.workout)
      ? `<div style="${S.dayBody}">${renderSections(day.workout.sections)}</div>`
      : '';

    return `<div style="${S.dayCard}">
  <div style="${S.dayHeader}">${header}</div>
  ${body}
</div>`;
  }).join('');

  return `${HTML_HEAD}
  <title>${plan.weekTitle} | FitForge AI</title>
</head>
<body>
  <div style="${S.page}">
    <div style="${S.pill}">● ${activeDays} Training Days · ${plan.goal}</div>
    <h1 style="${S.h1}">${plan.weekTitle}</h1>
    <p style="${S.subtitle}">Your personalised weekly training cycle</p>
    ${stripHtml}
    ${daysHtml}
    <div style="${S.footer}">© ${new Date().getFullYear()} FitForge AI · Generated ${new Date().toLocaleDateString()}</div>
  </div>
</body>
</html>`;
}




export function downloadFile(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type: `${type};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function downloadMarkdown(content: string, filename: string) {
  downloadFile(content, filename, 'text/markdown');
}

export async function downloadPdf(html: string, filename: string) {
  // A4 at 96 dpi
  const A4_W_PX  = 794;
  const A4_H_PX  = 1123;
  const SCALE    = 2;               // html2canvas render scale
  const A4_W_MM  = 210;
  const A4_H_MM  = 297;

  const iframe = document.createElement('iframe');
  iframe.style.cssText = [
    'position:fixed', 'top:0', 'left:-9999px',
    `width:${A4_W_PX}px`, `height:${A4_H_PX}px`,
    'border:none', 'visibility:hidden', 'overflow:hidden',
  ].join(';');
  document.body.appendChild(iframe);

  const doc = iframe.contentDocument || iframe.contentWindow?.document;
  if (!doc) { document.body.removeChild(iframe); return; }

  doc.open();
  doc.write(html);
  doc.close();

  // Wait for Google Fonts + layout
  await new Promise(resolve => setTimeout(resolve, 1600));

  // Expand iframe to full content height so html2canvas captures everything
  const totalContentH = doc.documentElement.scrollHeight;
  iframe.style.height = totalContentH + 'px';
  await new Promise(resolve => setTimeout(resolve, 120));

  try {
    // Capture the whole page as one canvas at 2× scale
    const canvas = await html2canvas(doc.body, {
      scale: SCALE,
      useCORS: true,
      logging: false,
      backgroundColor: '#1c1c20',
      width:  A4_W_PX,
      height: totalContentH,
      windowWidth: A4_W_PX,
    });

    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    // How many raw canvas pixels equal one A4 page height?
    const pageHeightCanvas = A4_H_PX * SCALE;
    const totalPages = Math.ceil(canvas.height / pageHeightCanvas);

    // Slice canvas into A4-page-height chunks, one chunk per PDF page
    const sliceCanvas  = document.createElement('canvas');
    sliceCanvas.width  = canvas.width;
    sliceCanvas.height = pageHeightCanvas;
    const ctx = sliceCanvas.getContext('2d')!;

    for (let page = 0; page < totalPages; page++) {
      if (page > 0) pdf.addPage();

      const srcY      = page * pageHeightCanvas;
      const srcH      = Math.min(pageHeightCanvas, canvas.height - srcY);

      // Fill background then draw the slice
      ctx.fillStyle = '#1c1c20';
      ctx.fillRect(0, 0, sliceCanvas.width, sliceCanvas.height);
      ctx.drawImage(
        canvas,
        0, srcY, canvas.width, srcH,   // source rect
        0, 0,    canvas.width, srcH,   // dest rect (top of slice canvas)
      );

      const sliceData = sliceCanvas.toDataURL('image/png');
      pdf.addImage(sliceData, 'PNG', 0, 0, A4_W_MM, A4_H_MM);
    }

    pdf.save(filename);
  } catch (error) {
    console.error('PDF generation failed:', error);
  } finally {
    document.body.removeChild(iframe);
  }
}

// ── Shareable link ────────────────────────────────────────────────────────────

export function encodeSharePayload(data: WeeklyPlan | Workout): string {
  const json = JSON.stringify(data);
  const encoded = btoa(encodeURIComponent(json));
  return encoded;
}

export function decodeSharePayload<T>(encoded: string): T | null {
  try {
    const json = decodeURIComponent(atob(encoded));
    return JSON.parse(json) as T;
  } catch {
    return null;
  }
}

export function buildShareUrl(data: WeeklyPlan | Workout, type: 'weekly' | 'single'): string {
  const encoded = encodeSharePayload(data);
  const base = typeof window !== 'undefined' ? window.location.origin : '';
  return `${base}/shared?type=${type}&plan=${encoded}`;
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}
